Vagrant.configure("2") do |config|

  config.vm.box = "hashicorp/bionic64"
  config.vm.box_version = "1.0.282"
  config.vm.box_check_update = false
  config.vm.network "forwarded_port", guest: 8000, host: 8000
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 5000, host: 5000
  config.vm.synced_folder ".", "/vagrant"
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get -qy update
    apt-get -qy install make zip unzip postgresql
    apt-get -qy install python3 python3-pip
  SHELL

  # Update password for postgres user:
  # sudo passwd postgres
  # (enter password (e.g. postgres))
  # 
  # su postgres -c 'createuser -dRS vagrant'
  # use password updated above
  # 
  # vagrant -c 'createdb'
  # vagrant -c 'createdb news'
  # vagrant -c 'createdb forum'
  # vagrant -c 'psql forum -f /vagrant/forum/forum.sql'

end
